name: Build

on:
  push:
    branches:
      - master

jobs:
  build-dot-net:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Install Amazon.Lambda.Tools
        run: dotnet tool install --tool-path ~/.dotnetamazon Amazon.Lambda.Tools
      - name: Restore "TV guide" dotnet packages
        run: dotnet restore src/aws-csharp.csproj
      - name: Package "TV guide"
        run: ~/.dotnetamazon/dotnet-lambda package --project-location src --configuration release --framework netcoreapp2.1 --output-package bin/release/netcoreapp2.1/epg.zip
  build-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
      - uses: actions/setup-node@master
      - name: Install serverless
        run: npm i -g serverless
      - name: install local dependencies
        run: npm ci
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Install serverless
  #       run: npm i -g serverless
  #     - name: install local dependencies
  #       run: npm ci
